### ISSUE TITLE
attachment patch .

### ISSUE THREAD

**Issue by xorgxx** [tomazahlin/symfony-mailer-bundle#6]
Hi i'm trying to attachment PDF by the patch not with the data.
how i can do this?

```
      $filename           = "yne-10003-facture.pdf";
      $patch               = 'files/orders/'.$filename;       
      $filename           = "yne-10003-facture.pdf";
      $contentType     = "pdf";
      $attachment      = new Attachment($patch, $filename, $contentType);
```
i get attachment in the email but i cant open.

thank

**Comment by xorgxx** [comment]
can you add : 
```
    foreach($this->attachments as $attachment) {
            $message->attach(\Swift_Attachment::fromPath($attachment->getData(), $attachment->getFilename(), $attachment->getContentType()));
        }
```
lake this all work. Maybe possible to add this ?

**Comment by xorgxx** [comment]
better : 
```
      foreach($this->attachments as $attachment) {
            if ( preg_match("/^[-a-z0-9+&@#\\/%?=~_|!:,.;]*$/",$attachment->getData()) ) {
                $message->attach(\Swift_Attachment::fromPath($attachment->getData(), $attachment->getFilename(), $attachment->getContentType()));
            }else{
                $message->attach(\Swift_Attachment::newInstance($attachment->getData(), $attachment->getFilename(), $attachment->getContentType()));
            }

        }
```

**Comment by studio3w** [comment]
Hello, example:

$attachment = new Attachment('test', 'test.txt', 'text');

First argument is the contents of the file, not the path to the file. (this is what you should fix, because you provide just a filename string, not contents)
Second argument is what the filename the user will see.
Third argument is the content type.

**Comment by studio3w** [comment]
And yes, what you mentioned, could also be done, to provide two ways how to construct an Attachment. From path, or by contents.

**Comment by tomazahlin** [comment]
Hello, example:

$attachment = new Attachment('test', 'test.txt', 'text');

First argument is the contents of the file, not the path to the file. (this is what you should fix, because you provide just a filename string, not contents)
Second argument is what the filename the user will see.
Third argument is the content type.

And yes, what you mentioned, could also be done, to provide two ways how to construct an Attachment. From path, or by contents.

**Comment by xorgxx** [comment]
or you planning to put this option?

**Comment by tomazahlin** [comment]
Not sure when I have the time, but it is possible. You can also do a PR. Did you solve your problem btw?

**Comment by xorgxx** [comment]
Yes i deed. with this in your code : 
```
      foreach($this->attachments as $attachment) {
            if ( preg_match("/^[-a-z0-9+&@#\\/%?=~_|!:,.;]*$/",$attachment->getData()) ) {
                $message->attach(\Swift_Attachment::fromPath($attachment->getData(), $attachment->getFilename(), $attachment->getContentType()));
            }else{
                $message->attach(\Swift_Attachment::newInstance($attachment->getData(), $attachment->getFilename(), $attachment->getContentType()));
            }

        }
```
